#!/usr/bin/env bash
i=0
while [ $i -le 10 ]
    do
        if [[ $i != 9 ]]
            then
                echo Best School
            else
                echo Hi
        fi
        ((i++))
    done
