#!/usr/bin/env bash
#cript that loops from 1 to 10
i=0
while [ $i -le 9 ]
    do
        if [[ $i == 3 ]]
            then
                echo bad luck
        elif [[ $i == 7 ]]
            then
            echo good luck
            else
                echo Best School
        fi
        ((i++))
    done
